name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select Environment
        type: choice
        options: [Development, Staging, Production]
        default: Development

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: 'poc-privatelink-func'
  AZURE_FUNCTIONAPP_PROJECT: './src/poc-private-link-func/poc-private-link-func.csproj'
  DOTNET_VERSION: '10.0.x'
  BUILD_ARTIFACT_NAME: 'released-package'

jobs:
  infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.env }}

    steps:
      - uses: actions/checkout@v4

      - name: 'Azure login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Show Az and Bicep versions'
        run: |
          az version
          az bicep version

      - name: 'Lint Bicep'
        run: |
          az bicep build \
            --file ./infra/azure-resources/main.bicep

      - name: 'Validate template'
        run: |
          az deployment group validate \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --parameters ./infra/azure-resources/main.${{ inputs.env }}.bicepparam

      - name: 'What-if preview'
        run: |
          az deployment group what-if \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --parameters ./infra/azure-resources/main.${{ inputs.env }}.bicepparam

      - name: 'Deploy Bicep'
        run: |
          az deployment group create \
            --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}" \
            --parameters ./infra/azure-resources/main.${{ inputs.env }}.bicepparam

  build:
    name: Build Application
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6

      - name: 'Set up .NET version: ${{ env.DOTNET_VERSION }}'
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build and prepare .NET project for deployment'
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PROJECT }} --configuration Release --output ./output

      - name: 'Upload artifact for the deployment job'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: output
          include-hidden-files: true

  

  application:
    name: Deploy Function App
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.env }}

    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: 'downloaded-artifact'

      - name: 'Log in to Azure with AZ CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run the Azure Functions action'
        uses: Azure/functions-action@v1
        id: deploy-to-function-app
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: 'downloaded-artifact'